warns = [
    "clippy::pedantic",
    "clippy::nursery"
]

allow = [
    "clippy::module_name_repetitions",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc"
]

deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::todo"
]

max_line_length = 120