max_width = 120
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
edition = "2024"
chain_width = 60
struct_lit_width = 40
use_field_init_shorthand = true
fn_params_layout = "Tall"
match_arm_leading_pipes = "Never"