[package]
name = "skju_emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
rand = "0.9.2"
skju_core = { path = "../skju_core" }